micronaut:
  application:
    name: phasmophobiaapi
  metrics:
    enabled: true
    export:
      influx:
        enabled: false
        step: PT1M

jackson:
  property-naming-strategy: SNAKE_CASE
  deserialization:
    fail-on-unknown-properties: false

phasmophobia:
  evidence-types:
    - name: "Ghost Writing"
      code: "GHOST_WRITING"
    - name: "Spirit Box"
      code: "SPIRIT_BOX"
    - name: "Fingerprints"
      code: "FINGERPRINTS"
    - name: "Freezing Temperatures"
      code: "FREEZING_TEMPERATURES"
    - name: "EMF Level 5"
      code: "EMF_LEVEL_FIVE"
    - name: "Ghost Orbs"
      code: "GHOST_ORBS"
    - name: "D.O.T.S Projector"
      code: "DOTS_PROJECTOR"
  ghost-types:
    - name: "Spirit"
      code: "SPIRIT"
      evidence_codes:
        - "SPIRIT_BOX"
        - "GHOST_WRITING"
        - "EMF_LEVEL_FIVE"
    - name: "Poltergeist"
      code: "POLTERGEIST"
      evidence_codes:
        - "GHOST_WRITING"
        - "SPIRIT_BOX"
        - "FINGERPRINTS"
    - name: "Oni"
      code: "ONI"
      evidence_codes:
        - "EMF_LEVEL_FIVE"
        - "DOTS_PROJECTOR"
        - "FREEZING_TEMPERATURES"
    - name: "Shade"
      code: "SHADE"
      evidence_codes:
        - "EMF_LEVEL_FIVE"
        - "FREEZING_TEMPERATURES"
        - "GHOST_WRITING"
    - name: "Jinn"
      code: "JINN"
      evidence_codes:
        - "EMF_LEVEL_FIVE"
        - "FINGERPRINTS"
        - "FREEZING_TEMPERATURES"
    - name: "Wraith"
      code: "WRAITH"
      evidence_codes:
        - "DOTS_PROJECTOR"
        - "EMF_LEVEL_FIVE"
        - "SPIRIT_BOX"
    - name: "Demon"
      code: "DEMON"
      evidence_codes:
        - "FREEZING_TEMPERATURES"
        - "GHOST_WRITING"
        - "FINGERPRINTS"
    - name: "Yurei"
      code: "YUREI"
      evidence_codes:
        - "FREEZING_TEMPERATURES"
        - "DOTS_PROJECTOR"
        - "GHOST_ORBS"
    - name: "Mare"
      code: "MARE"
      evidence_codes:
        - "GHOST_WRITING"
        - "SPIRIT_BOX"
        - "GHOST_ORBS"
    - name: "Banshee"
      code: "BANSHEE"
      evidence_codes:
        - "GHOST_ORBS"
        - "DOTS_PROJECTOR"
        - "FINGERPRINTS"
    - name: "Phantom"
      code: "PHANTOM"
      evidence_codes:
        - "SPIRIT_BOX"
        - "FINGERPRINTS"
        - "DOTS_PROJECTOR"
    - name: "Revenant"
      code: "REVENANT"
      evidence_codes:
        - "GHOST_ORBS"
        - "GHOST_WRITING"
        - "FREEZING_TEMPERATURES"
    - name: "Yokai"
      code: "YOKAI"
      evidence_codes:
        - "SPIRIT_BOX"
        - "GHOST_ORBS"
        - "DOTS_PROJECTOR"
    - name: "Hantu"
      code: "HANTU"
      evidence_codes:
        - "FINGERPRINTS"
        - "GHOST_ORBS"
        - "FREEZING_TEMPERATURES"
